### ISSUE TITLE
local audio yomichan is suddenly won't work.

### ISSUE THREAD

**Issue by ghost** [yomidevs/local-audio-yomichan#18]
Anki 23.10 (51a10f09) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-08 04:25:50

When loading Local Audio Server for Yomichan:
Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1045800357\__init__.py", line 9, in <module>
    run_server()
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\1045800357\server.py", line 210, in run_server
    httpd = http.server.ThreadingHTTPServer((HOSTNAME, PORT), LocalAudioHandler)
  File "socketserver", line 452, in __init__
  File "http.server", line 136, in server_bind
  File "socketserver", line 466, in server_bind
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

**Comment by Kuuuube** [comment]
Closing as this user's github account no longer exists.
